# Generated by Django 5.1.6 on 2025-06-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_coursecontent_coursemember_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nama kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='deskripsi')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='warna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nama tag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='disetujui'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maksimal Siswa'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='dipublikasi'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='waktu rilis'),
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul diskusi')),
                ('description', models.TextField(verbose_name='deskripsi')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='disematkan')),
                ('is_locked', models.BooleanField(default=False, verbose_name='dikunci')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='penulis')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.course', verbose_name='kursus')),
            ],
            options={
                'verbose_name': 'Thread Diskusi',
                'verbose_name_plural': 'Thread Diskusi',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='konten')),
                ('is_solution', models.BooleanField(default=False, verbose_name='solusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='penulis')),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_core.discussionreply', verbose_name='balasan induk')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.discussionthread', verbose_name='thread')),
            ],
            options={
                'verbose_name': 'Balasan Diskusi',
                'verbose_name_plural': 'Balasan Diskusi',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul')),
                ('message', models.TextField(verbose_name='pesan')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('new_content', 'New Content'), ('assignment', 'Assignment'), ('discussion', 'Discussion'), ('comment', 'Comment'), ('completion', 'Completion'), ('certificate', 'Certificate'), ('announcement', 'Announcement')], default='announcement', max_length=20, verbose_name='tipe')),
                ('is_read', models.BooleanField(default=False, verbose_name='sudah dibaca')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL aksi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='penerima')),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent', verbose_name='konten terkait')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_core.course', verbose_name='kursus terkait')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='pengirim')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='notifikasi email')),
                ('enrollment_notifications', models.BooleanField(default=True, verbose_name='notifikasi enrollment')),
                ('content_notifications', models.BooleanField(default=True, verbose_name='notifikasi konten baru')),
                ('discussion_notifications', models.BooleanField(default=True, verbose_name='notifikasi diskusi')),
                ('comment_notifications', models.BooleanField(default=True, verbose_name='notifikasi komentar')),
                ('completion_notifications', models.BooleanField(default=True, verbose_name='notifikasi penyelesaian')),
                ('announcement_notifications', models.BooleanField(default=True, verbose_name='notifikasi pengumuman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'Preferensi Notifikasi',
                'verbose_name_plural': 'Preferensi Notifikasi',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent', verbose_name='konten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='CompletionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='diselesaikan pada')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent', verbose_name='konten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'Tracking Penyelesaian',
                'verbose_name_plural': 'Tracking Penyelesaian',
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.category', verbose_name='kategori')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.course', verbose_name='kursus')),
            ],
            options={
                'verbose_name': 'Kategori Kursus',
                'verbose_name_plural': 'Kategori Kursus',
                'unique_together': {('course', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent', verbose_name='konten')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Tag Konten',
                'verbose_name_plural': 'Tag Konten',
                'unique_together': {('content', 'tag')},
            },
        ),
    ]
