# Generated by Django 5.1.6 on 2025-07-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0004_category_tag_comment_is_approved_course_max_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('new_content', 'New Content'), ('assignment', 'Assignment'), ('discussion', 'Discussion'), ('comment', 'Comment'), ('completion', 'Completion'), ('announcement', 'Announcement')], default='announcement', max_length=20, verbose_name='tipe'),
        ),
    ]
